  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
name: Automate Everything with Supabase

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  automate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          if [ -f package.json ]; then
            npm ci
          fi

      - name: Install Supabase CLI
        run: npm install -g supabase

      - name: Supabase login
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: supabase login $SUPABASE_ACCESS_TOKEN

      - name: Deploy Edge Functions (if present)
        run: |
          if [ -d "supabase/functions" ]; then
            for fn in supabase/functions/*; do
              if [ -d "$fn" ]; then
                supabase functions deploy $(basename "$fn")
              fi
            done
          fi

      - name: Push database migrations (if present)
        run: |
          if [ -d "supabase/migrations" ]; then
            supabase db push
          fi

      - name: Run tests (if present)
        run: |
          if [ -f package.json ]; then
            npm test || true
          fi

      # OPTIONAL: Build frontend (add your build commands here)
      # - name: Build frontend
      #   run: npm run build

      # OPTIONAL: Deploy frontend (add your deployment commands here)
      
